a=int(input("Ingrese el primer numero: "))
b=int(input("Ingrese el segundo numero: "))
print("La suma de", a , "y",b, "es:", a + b )
print("La division de", a , "y" , b , "es:", a/b)
print("Es divisor:", b % a == 0 )
print("El 10% de",a,"es:", a//10)
