cadena = input( "Ingrese una cadena de texto: " )
print("la longitud de la cadena es", len(cadena))
print("contiene 'la':", "la" in cadena)
print("cadena en mayusculas", cadena.upper())
vocales = cadena.count("a") + cadena.count("e") + cadena.count("i") + cadena.count("o") + cadena.count("u")
print("vocales en minusculas", vocales)
