name: Python Code Compliance

on:
  push:
  pull_request:

jobs:
  python-compliance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install pylint pytest
          
      - name: Run tests
        run: |
          pytest -v test/

      - name: Run pylint
        run: |
          pylint src/
